//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocietyPass.Mobile.Core.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SocietyPass.Mobile.Core.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should start playing the movie now.
        /// </summary>
        internal static string AlertMessageMovieShouldPlayMovieNow {
            get {
                return ResourceManager.GetString("AlertMessageMovieShouldPlayMovieNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movie Tapped!.
        /// </summary>
        internal static string AlertTitleMovieTapped {
            get {
                return ResourceManager.GetString("AlertTitleMovieTapped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enjoy it now!.
        /// </summary>
        internal static string BannerBodyEnjoyItNow {
            get {
                return ResourceManager.GetString("BannerBodyEnjoyItNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 25% discount.
        /// </summary>
        internal static string BannerTitle25DiscOff {
            get {
                return ResourceManager.GetString("BannerTitle25DiscOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Comment.
        /// </summary>
        internal static string ButtonAddComment {
            get {
                return ResourceManager.GetString("ButtonAddComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to cart.
        /// </summary>
        internal static string ButtonAddToCart {
            get {
                return ResourceManager.GetString("ButtonAddToCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already a user? Login now.
        /// </summary>
        internal static string ButtonAlreadyUserLoginNow {
            get {
                return ResourceManager.GetString("ButtonAlreadyUserLoginNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse our samples.
        /// </summary>
        internal static string ButtonBrowseOurSamples {
            get {
                return ResourceManager.GetString("ButtonBrowseOurSamples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string ButtonDefault {
            get {
                return ResourceManager.GetString("ButtonDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string ButtonDelete {
            get {
                return ResourceManager.GetString("ButtonDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Account.
        /// </summary>
        internal static string ButtonDeleteAccount {
            get {
                return ResourceManager.GetString("ButtonDeleteAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        internal static string ButtonMore {
            get {
                return ResourceManager.GetString("ButtonMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Movie.
        /// </summary>
        internal static string ButtonPlayMovie {
            get {
                return ResourceManager.GetString("ButtonPlayMovie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Action.
        /// </summary>
        internal static string ButtonPrimaryAction {
            get {
                return ResourceManager.GetString("ButtonPrimaryAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string ButtonSave {
            get {
                return ResourceManager.GetString("ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary Action.
        /// </summary>
        internal static string ButtonSecondaryAction {
            get {
                return ResourceManager.GetString("ButtonSecondaryAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See our walkthrough.
        /// </summary>
        internal static string ButtonSeeOurWalkThrough {
            get {
                return ResourceManager.GetString("ButtonSeeOurWalkThrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m an Editor 
        ///and I love multiple lines! ;).
        /// </summary>
        internal static string EditorSampleText {
            get {
                return ResourceManager.GetString("EditorSampleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        internal static string EntryCellPlaceholderPhoneNumber {
            get {
                return ResourceManager.GetString("EntryCellPlaceholderPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to robert.stainford@uxdivers.com.
        /// </summary>
        internal static string EntryCellSampleEmail {
            get {
                return ResourceManager.GetString("EntryCellSampleEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid e-mail.
        /// </summary>
        internal static string ErrorPleaseEnterValidEmail {
            get {
                return ResourceManager.GetString("ErrorPleaseEnterValidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50 days logged in.
        /// </summary>
        internal static string ImageCellDetailDaysLoggedIn {
            get {
                return ResourceManager.GetString("ImageCellDetailDaysLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VS Studio PartnerWe are a team of passionate UX/UI Designers and Developers with only one mission: help developers make appealing good applications better and 
        ///faster while we have fun doing what we love..
        /// </summary>
        internal static string LabelAboutUsText {
            get {
                return ResourceManager.GetString("LabelAboutUsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActivityIndicators.
        /// </summary>
        internal static string LabelActivityIndicators {
            get {
                return ResourceManager.GetString("LabelActivityIndicators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artina Buttons.
        /// </summary>
        internal static string LabelArtinaButtons {
            get {
                return ResourceManager.GetString("LabelArtinaButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artina Entry.
        /// </summary>
        internal static string LabelArtinaEntry {
            get {
                return ResourceManager.GetString("LabelArtinaEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Badge.
        /// </summary>
        internal static string LabelBadge {
            get {
                return ResourceManager.GetString("LabelBadge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BrandBlock.
        /// </summary>
        internal static string LabelBrandBlock {
            get {
                return ResourceManager.GetString("LabelBrandBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buttons.
        /// </summary>
        internal static string LabelButtons {
            get {
                return ResourceManager.GetString("LabelButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CircleImages.
        /// </summary>
        internal static string LabelCircleImages {
            get {
                return ResourceManager.GetString("LabelCircleImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Image Cache.
        /// </summary>
        internal static string LabelClearImageCache {
            get {
                return ResourceManager.GetString("LabelClearImageCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits.
        /// </summary>
        internal static string LabelCredits {
            get {
                return ResourceManager.GetString("LabelCredits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note the Menu displayed on top ;).
        /// </summary>
        internal static string LabelCustomavBarNoteMenu {
            get {
                return ResourceManager.GetString("LabelCustomavBarNoteMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom NavBar.
        /// </summary>
        internal static string LabelCustomNavBar {
            get {
                return ResourceManager.GetString("LabelCustomNavBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The NavBar on this page is totally custom which means you could add as many icons as you need and combine it with other views such as badges, etc..
        /// </summary>
        internal static string LabelCustomNavBarText {
            get {
                return ResourceManager.GetString("LabelCustomNavBarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Global issues.
        /// </summary>
        internal static string LabelDisplayGlobalIssues {
            get {
                return ResourceManager.GetString("LabelDisplayGlobalIssues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entries And Editors.
        /// </summary>
        internal static string LabelEntriesAndEditors {
            get {
                return ResourceManager.GetString("LabelEntriesAndEditors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        internal static string LabelForgotYourPassword {
            get {
                return ResourceManager.GetString("LabelForgotYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t worry type your email here and we will recover it for you..
        /// </summary>
        internal static string LabelForgotYourPasswordExplained {
            get {
                return ResourceManager.GetString("LabelForgotYourPasswordExplained", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frames.
        /// </summary>
        internal static string LabelFrames {
            get {
                return ResourceManager.GetString("LabelFrames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ListView and SearchBar.
        /// </summary>
        internal static string LabelListViewAndSearchBar {
            get {
                return ResourceManager.GetString("LabelListViewAndSearchBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login or register using your email and password..
        /// </summary>
        internal static string LabelLoginOrRegisterUsinMailOrPass {
            get {
                return ResourceManager.GetString("LabelLoginOrRegisterUsinMailOrPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need custom animations?.
        /// </summary>
        internal static string LabelNeedCustomAnimations {
            get {
                return ResourceManager.GetString("LabelNeedCustomAnimations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or connect with.
        /// </summary>
        internal static string LabelOrConnectWith {
            get {
                return ResourceManager.GetString("LabelOrConnectWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Products.
        /// </summary>
        internal static string LabelOurProducts {
            get {
                return ResourceManager.GetString("LabelOurProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Society Pass UI Kit and Gorilla Player for Xamarin.Forms
        ///had been helping developers build better and good looking apps faster since 2015.
        ///Stay tunned we have more surprises coming soon….
        /// </summary>
        internal static string LabelOurProductsLongText {
            get {
                return ResourceManager.GetString("LabelOurProductsLongText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passion driven designer and developer. Frustrated musician and father of two..
        /// </summary>
        internal static string LabelPassionDrivenDesigner {
            get {
                return ResourceManager.GetString("LabelPassionDrivenDesigner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match.
        /// </summary>
        internal static string LabelPasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("LabelPasswordsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photography is my passion. Black and white is the way I see the world..
        /// </summary>
        internal static string LabelPhotographyIsMyPassion {
            get {
                return ResourceManager.GetString("LabelPhotographyIsMyPassion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pickers.
        /// </summary>
        internal static string LabelPickers {
            get {
                return ResourceManager.GetString("LabelPickers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string LabelPlaceholderEmail {
            get {
                return ResourceManager.GetString("LabelPlaceholderEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProgressBars.
        /// </summary>
        internal static string LabelProgressBars {
            get {
                return ResourceManager.GetString("LabelProgressBars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register now.
        /// </summary>
        internal static string LabelRegisterNow {
            get {
                return ResourceManager.GetString("LabelRegisterNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register now and enjoy the pleasures of the demo..
        /// </summary>
        internal static string LabelRegisterNowAndEnjoy {
            get {
                return ResourceManager.GetString("LabelRegisterNowAndEnjoy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat Password.
        /// </summary>
        internal static string LabelRepeatPassword {
            get {
                return ResourceManager.GetString("LabelRepeatPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RoundedLabel.
        /// </summary>
        internal static string LabelRoundedLabel {
            get {
                return ResourceManager.GetString("LabelRoundedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sliders.
        /// </summary>
        internal static string LabelSliders {
            get {
                return ResourceManager.GetString("LabelSliders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special thanks.
        /// </summary>
        internal static string LabelSpecialThanks {
            get {
                return ResourceManager.GetString("LabelSpecialThanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switches.
        /// </summary>
        internal static string LabelSwitches {
            get {
                return ResourceManager.GetString("LabelSwitches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take your app to the next level with The Society Pass UI Kit..
        /// </summary>
        internal static string LabelTakeYourAppToNextLevel {
            get {
                return ResourceManager.GetString("LabelTakeYourAppToNextLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s nothing here my friend :).
        /// </summary>
        internal static string LabelThereIsNothingHere {
            get {
                return ResourceManager.GetString("LabelThereIsNothingHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a frame containing a Label control.
        /// </summary>
        internal static string LabelThisIsAFrameDescription {
            get {
                return ResourceManager.GetString("LabelThisIsAFrameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use your credentials to login..
        /// </summary>
        internal static string LabelUseCredentialsToLogin {
            get {
                return ResourceManager.GetString("LabelUseCredentialsToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I like my toast done on one side..
        /// </summary>
        internal static string LabelUserDescriptionVariant {
            get {
                return ResourceManager.GetString("LabelUserDescriptionVariant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation Entry Error Style.
        /// </summary>
        internal static string LabelValidationEntryErrorStyle {
            get {
                return ResourceManager.GetString("LabelValidationEntryErrorStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VS Studio Partner.
        /// </summary>
        internal static string LabelVisualStudioPartner {
            get {
                return ResourceManager.GetString("LabelVisualStudioPartner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As partners of the greatest IDE ever, we are commited to deliver high quality products that really help devs to achieve their best..
        /// </summary>
        internal static string LabelVisualStudioPartnerLongText {
            get {
                return ResourceManager.GetString("LabelVisualStudioPartnerLongText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are a team of passionate UX/UI Designers and Developers with only one mission: help developers make appealing good applications better and 
        ///faster while we have fun doing what we love..
        /// </summary>
        internal static string LabelWeAreATeamOfPassionate {
            get {
                return ResourceManager.GetString("LabelWeAreATeamOfPassionate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to The Society Pass.Starter.
        /// </summary>
        internal static string LabelWelcomeToSocietyPassStarter {
            get {
                return ResourceManager.GetString("LabelWelcomeToSocietyPassStarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to The Society Pass Starter. You are all setup and ready to rock!.
        /// </summary>
        internal static string LabelWelcomeToSocietyPassStarterDescription {
            get {
                return ResourceManager.GetString("LabelWelcomeToSocietyPassStarterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes! The Society Pass UI Kit now supports Lottie Animations out of the box..
        /// </summary>
        internal static string LabelYesSocietyPassSupportsLottie {
            get {
                return ResourceManager.GetString("LabelYesSocietyPassSupportsLottie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icons Dashboard.
        /// </summary>
        internal static string PageMenuTitleDashboardIcons {
            get {
                return ResourceManager.GetString("PageMenuTitleDashboardIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generic About Page.
        /// </summary>
        internal static string PageTitleAbout {
            get {
                return ResourceManager.GetString("PageTitleAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Society Pass Android TabControl.
        /// </summary>
        internal static string PageTitleAndroidTabControl {
            get {
                return ResourceManager.GetString("PageTitleAndroidTabControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animation.
        /// </summary>
        internal static string PageTitleAnimation {
            get {
                return ResourceManager.GetString("PageTitleAnimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Articles Classic View.
        /// </summary>
        internal static string PageTitleArticleClassicView {
            get {
                return ResourceManager.GetString("PageTitleArticleClassicView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Articles List.
        /// </summary>
        internal static string PageTitleArticleList {
            get {
                return ResourceManager.GetString("PageTitleArticleList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Articles Feed.
        /// </summary>
        internal static string PageTitleArticlesFeed {
            get {
                return ResourceManager.GetString("PageTitleArticlesFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Articles List Variant.
        /// </summary>
        internal static string PageTitleArticlesListVariant {
            get {
                return ResourceManager.GetString("PageTitleArticlesListVariant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article View.
        /// </summary>
        internal static string PageTitleArticleView {
            get {
                return ResourceManager.GetString("PageTitleArticleView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Society Pass Bottom TabControl.
        /// </summary>
        internal static string PageTitleBottomTabControl {
            get {
                return ResourceManager.GetString("PageTitleBottomTabControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cards List.
        /// </summary>
        internal static string PageTitleCardsList {
            get {
                return ResourceManager.GetString("PageTitleCardsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories List Flat.
        /// </summary>
        internal static string PageTitleCategoriesListFlat {
            get {
                return ResourceManager.GetString("PageTitleCategoriesListFlat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon Categories.
        /// </summary>
        internal static string PageTitleCategoriesListWithIcons {
            get {
                return ResourceManager.GetString("PageTitleCategoriesListWithIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Categories.
        /// </summary>
        internal static string PageTitleCategoryListImages {
            get {
                return ResourceManager.GetString("PageTitleCategoryListImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat Messages List.
        /// </summary>
        internal static string PageTitleChatMessageList {
            get {
                return ResourceManager.GetString("PageTitleChatMessageList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat Timeline.
        /// </summary>
        internal static string PageTitleChatTimeLine {
            get {
                return ResourceManager.GetString("PageTitleChatTimeLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Society Pass Common Views.
        /// </summary>
        internal static string PageTitleCommonViews {
            get {
                return ResourceManager.GetString("PageTitleCommonViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Activity Indicator.
        /// </summary>
        internal static string PageTitleCustomActivityIndicator {
            get {
                return ResourceManager.GetString("PageTitleCustomActivityIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom NavBar.
        /// </summary>
        internal static string PageTitleCustomNavBar {
            get {
                return ResourceManager.GetString("PageTitleCustomNavBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Renderers.
        /// </summary>
        internal static string PageTitleCustomRenderers {
            get {
                return ResourceManager.GetString("PageTitleCustomRenderers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Settings Page.
        /// </summary>
        internal static string PageTitleCustomSettings {
            get {
                return ResourceManager.GetString("PageTitleCustomSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard Cards.
        /// </summary>
        internal static string PageTitleDashboardCards {
            get {
                return ResourceManager.GetString("PageTitleDashboardCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flat Dashboard.
        /// </summary>
        internal static string PageTitleDashboardFlat {
            get {
                return ResourceManager.GetString("PageTitleDashboardFlat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string PageTitleDashboardIcons {
            get {
                return ResourceManager.GetString("PageTitleDashboardIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard Multiple Scroll.
        /// </summary>
        internal static string PageTitleDashboardMultipleScroll {
            get {
                return ResourceManager.GetString("PageTitleDashboardMultipleScroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple Tiles.
        /// </summary>
        internal static string PageTitleDashboardMultipleTiles {
            get {
                return ResourceManager.GetString("PageTitleDashboardMultipleTiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard Scrollable.
        /// </summary>
        internal static string PageTitleDashboardScrollable {
            get {
                return ResourceManager.GetString("PageTitleDashboardScrollable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images Dashboard.
        /// </summary>
        internal static string PageTitleDashboardWithImages {
            get {
                return ResourceManager.GetString("PageTitleDashboardWithImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Timeline.
        /// </summary>
        internal static string PageTitleDocumentTimeline {
            get {
                return ResourceManager.GetString("PageTitleDocumentTimeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty State.
        /// </summary>
        internal static string PageTitleEmptyState {
            get {
                return ResourceManager.GetString("PageTitleEmptyState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front Page News.
        /// </summary>
        internal static string PageTitleFrontPageNews {
            get {
                return ResourceManager.GetString("PageTitleFrontPageNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Society Pass iOS TabControl.
        /// </summary>
        internal static string PageTitleiOSTabControl {
            get {
                return ResourceManager.GetString("PageTitleiOSTabControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string PageTitleLogin {
            get {
                return ResourceManager.GetString("PageTitleLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Menu.
        /// </summary>
        internal static string PageTitleMainMenu {
            get {
                return ResourceManager.GetString("PageTitleMainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        internal static string PageTitleMessages {
            get {
                return ResourceManager.GetString("PageTitleMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movie Selection.
        /// </summary>
        internal static string PageTitleMovieSelection {
            get {
                return ResourceManager.GetString("PageTitleMovieSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Native Controls.
        /// </summary>
        internal static string PageTitleNativeControls {
            get {
                return ResourceManager.GetString("PageTitleNativeControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Recovery.
        /// </summary>
        internal static string PageTitlePasswordRecovery {
            get {
                return ResourceManager.GetString("PageTitlePasswordRecovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products Grid.
        /// </summary>
        internal static string PageTitleProductGrid {
            get {
                return ResourceManager.GetString("PageTitleProductGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products Grid Variant.
        /// </summary>
        internal static string PageTitleProductGridVariant {
            get {
                return ResourceManager.GetString("PageTitleProductGridVariant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Order.
        /// </summary>
        internal static string PageTitleProductOrder {
            get {
                return ResourceManager.GetString("PageTitleProductOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products Catalog.
        /// </summary>
        internal static string PageTitleProductsCatalog {
            get {
                return ResourceManager.GetString("PageTitleProductsCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string PageTitleProfile {
            get {
                return ResourceManager.GetString("PageTitleProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Chat List.
        /// </summary>
        internal static string PageTitleRecentChatList {
            get {
                return ResourceManager.GetString("PageTitleRecentChatList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsive Helpers.
        /// </summary>
        internal static string PageTitleResponsiveHelpers {
            get {
                return ResourceManager.GetString("PageTitleResponsiveHelpers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings Page.
        /// </summary>
        internal static string PageTitleSettings {
            get {
                return ResourceManager.GetString("PageTitleSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        internal static string PageTitleSignup {
            get {
                return ResourceManager.GetString("PageTitleSignup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple Login.
        /// </summary>
        internal static string PageTitleSimpleLogin {
            get {
                return ResourceManager.GetString("PageTitleSimpleLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple Sign Up.
        /// </summary>
        internal static string PageTitleSimpleSignup {
            get {
                return ResourceManager.GetString("PageTitleSimpleSignup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social.
        /// </summary>
        internal static string PageTitleSocial {
            get {
                return ResourceManager.GetString("PageTitleSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Variant.
        /// </summary>
        internal static string PageTitleSocialVariant {
            get {
                return ResourceManager.GetString("PageTitleSocialVariant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabbed Page.
        /// </summary>
        internal static string PageTitleTabbedPage {
            get {
                return ResourceManager.GetString("PageTitleTabbedPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Society Pass TabControl.
        /// </summary>
        internal static string PageTitleTabControl {
            get {
                return ResourceManager.GetString("PageTitleTabControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme Icons Preview.
        /// </summary>
        internal static string PageTitleThemeFontIcons {
            get {
                return ResourceManager.GetString("PageTitleThemeFontIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Society Pass Themes Preview.
        /// </summary>
        internal static string PageTitleThemesPreview {
            get {
                return ResourceManager.GetString("PageTitleThemesPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeline.
        /// </summary>
        internal static string PageTitleTimeline {
            get {
                return ResourceManager.GetString("PageTitleTimeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        internal static string PageTitleTitleNotifications {
            get {
                return ResourceManager.GetString("PageTitleTitleNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebView.
        /// </summary>
        internal static string PageTitleWebview {
            get {
                return ResourceManager.GetString("PageTitleWebview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome Page.
        /// </summary>
        internal static string PageTitleWelcome {
            get {
                return ResourceManager.GetString("PageTitleWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome Starter.
        /// </summary>
        internal static string PageTitleWelcomeStarter {
            get {
                return ResourceManager.GetString("PageTitleWelcomeStarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m a Picker!.
        /// </summary>
        internal static string PickerTitleSample {
            get {
                return ResourceManager.GetString("PickerTitleSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAST.
        /// </summary>
        internal static string RoundedLabelCast {
            get {
                return ResourceManager.GetString("RoundedLabelCast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DIRECTOR.
        /// </summary>
        internal static string RoundedLabelDirector {
            get {
                return ResourceManager.GetString("RoundedLabelDirector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Society Pass Rounded Label Sample.
        /// </summary>
        internal static string RoundedLabelTextSample {
            get {
                return ResourceManager.GetString("RoundedLabelTextSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Society Pass Movies.
        /// </summary>
        internal static string SampleDashboardSocietyPassMovies {
            get {
                return ResourceManager.GetString("SampleDashboardSocietyPassMovies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products Carousel.
        /// </summary>
        internal static string SampleProductCarousel {
            get {
                return ResourceManager.GetString("SampleProductCarousel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product FullScreen.
        /// </summary>
        internal static string SampleProductFullscreen {
            get {
                return ResourceManager.GetString("SampleProductFullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Item View.
        /// </summary>
        internal static string SampleProductItemView {
            get {
                return ResourceManager.GetString("SampleProductItemView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root Page.
        /// </summary>
        internal static string SampleTitleRootPage {
            get {
                return ResourceManager.GetString("SampleTitleRootPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demo Settings.
        /// </summary>
        internal static string SampleTitleThemeDemoSettings {
            get {
                return ResourceManager.GetString("SampleTitleThemeDemoSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walkthrough.
        /// </summary>
        internal static string SampleTitleWalkthrough {
            get {
                return ResourceManager.GetString("SampleTitleWalkthrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walkthrough Flat.
        /// </summary>
        internal static string SampleTitleWalkthroughFlat {
            get {
                return ResourceManager.GetString("SampleTitleWalkthroughFlat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walkthrough Variant.
        /// </summary>
        internal static string SampleTitleWalkthroughVariant {
            get {
                return ResourceManager.GetString("SampleTitleWalkthroughVariant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Profile.
        /// </summary>
        internal static string SampleUserProfile {
            get {
                return ResourceManager.GetString("SampleUserProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for a name.
        /// </summary>
        internal static string SearchBarPlaceholderSearchForAName {
            get {
                return ResourceManager.GetString("SearchBarPlaceholderSearchForAName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string StringAddress {
            get {
                return ResourceManager.GetString("StringAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Line 1.
        /// </summary>
        internal static string StringAddress1 {
            get {
                return ResourceManager.GetString("StringAddress1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Line 2.
        /// </summary>
        internal static string StringAddress2 {
            get {
                return ResourceManager.GetString("StringAddress2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string StringApply {
            get {
                return ResourceManager.GetString("StringApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batman&apos;s choice.
        /// </summary>
        internal static string StringBatmanChoice {
            get {
                return ResourceManager.GetString("StringBatmanChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy.
        /// </summary>
        internal static string StringBuy {
            get {
                return ResourceManager.GetString("StringBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call the experts.
        /// </summary>
        internal static string StringCallTheExperts {
            get {
                return ResourceManager.GetString("StringCallTheExperts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t reach your current location.
        /// </summary>
        internal static string StringCantReachLocation {
            get {
                return ResourceManager.GetString("StringCantReachLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Number.
        /// </summary>
        internal static string StringCardNumber {
            get {
                return ResourceManager.GetString("StringCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Articles.
        /// </summary>
        internal static string StringCategoryArticles {
            get {
                return ResourceManager.GetString("StringCategoryArticles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboards.
        /// </summary>
        internal static string StringCategoryDashboards {
            get {
                return ResourceManager.GetString("StringCategoryDashboards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ECommerce.
        /// </summary>
        internal static string StringCategoryECommerce {
            get {
                return ResourceManager.GetString("StringCategoryECommerce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logins.
        /// </summary>
        internal static string StringCategoryLogins {
            get {
                return ResourceManager.GetString("StringCategoryLogins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        internal static string StringCategoryMessages {
            get {
                return ResourceManager.GetString("StringCategoryMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation.
        /// </summary>
        internal static string StringCategoryNavigation {
            get {
                return ResourceManager.GetString("StringCategoryNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social.
        /// </summary>
        internal static string StringCategorySocial {
            get {
                return ResourceManager.GetString("StringCategorySocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        internal static string StringCategoryTheme {
            get {
                return ResourceManager.GetString("StringCategoryTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walkthroughs.
        /// </summary>
        internal static string StringCategoryWalkthroughs {
            get {
                return ResourceManager.GetString("StringCategoryWalkthroughs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string StringCity {
            get {
                return ResourceManager.GetString("StringCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clare Japi.
        /// </summary>
        internal static string StringClareJapi {
            get {
                return ResourceManager.GetString("StringClareJapi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ,.
        /// </summary>
        internal static string StringColon {
            get {
                return ResourceManager.GetString("StringColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare.
        /// </summary>
        internal static string StringCompare {
            get {
                return ResourceManager.GetString("StringCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        internal static string StringConfirmation {
            get {
                return ResourceManager.GetString("StringConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect Your Account.
        /// </summary>
        internal static string StringConnectYourAccount {
            get {
                return ResourceManager.GetString("StringConnectYourAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        internal static string StringContact {
            get {
                return ResourceManager.GetString("StringContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Context Action Tapped.
        /// </summary>
        internal static string StringContextActionTapped {
            get {
                return ResourceManager.GetString("StringContextActionTapped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string StringCountry {
            get {
                return ResourceManager.GetString("StringCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom ?.
        /// </summary>
        internal static string StringCustom {
            get {
                return ResourceManager.GetString("StringCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CVC.
        /// </summary>
        internal static string StringCVC {
            get {
                return ResourceManager.GetString("StringCVC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        internal static string StringDark {
            get {
                return ResourceManager.GetString("StringDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DarkTheme.
        /// </summary>
        internal static string StringDarkTheme {
            get {
                return ResourceManager.GetString("StringDarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string StringDone {
            get {
                return ResourceManager.GetString("StringDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string StringEmail {
            get {
                return ResourceManager.GetString("StringEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enterprise.
        /// </summary>
        internal static string StringEnterprise {
            get {
                return ResourceManager.GetString("StringEnterprise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnterpriseTheme.
        /// </summary>
        internal static string StringEnterpriseTheme {
            get {
                return ResourceManager.GetString("StringEnterpriseTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string StringError {
            get {
                return ResourceManager.GetString("StringError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration Date.
        /// </summary>
        internal static string StringExpirationDate {
            get {
                return ResourceManager.GetString("StringExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra soft UI flavor.
        /// </summary>
        internal static string StringExtraSoftUIFlavor {
            get {
                return ResourceManager.GetString("StringExtraSoftUIFlavor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook.
        /// </summary>
        internal static string StringFacebook {
            get {
                return ResourceManager.GetString("StringFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish!.
        /// </summary>
        internal static string StringFinish {
            get {
                return ResourceManager.GetString("StringFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FRIENDS.
        /// </summary>
        internal static string StringFriends {
            get {
                return ResourceManager.GetString("StringFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give us a call.
        /// </summary>
        internal static string StringGiveUsACall {
            get {
                return ResourceManager.GetString("StringGiveUsACall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello Clare!.
        /// </summary>
        internal static string StringHelloClare {
            get {
                return ResourceManager.GetString("StringHelloClare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icons.
        /// </summary>
        internal static string StringIcons {
            get {
                return ResourceManager.GetString("StringIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impress your boss.
        /// </summary>
        internal static string StringImpressYourBoss {
            get {
                return ResourceManager.GetString("StringImpressYourBoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string StringLastName {
            get {
                return ResourceManager.GetString("StringLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        internal static string StringLight {
            get {
                return ResourceManager.GetString("StringLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LightTheme.
        /// </summary>
        internal static string StringLightTheme {
            get {
                return ResourceManager.GetString("StringLightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linkedin.
        /// </summary>
        internal static string StringLinkedin {
            get {
                return ResourceManager.GetString("StringLinkedin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string StringLoading {
            get {
                return ResourceManager.GetString("StringLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string StringLogin {
            get {
                return ResourceManager.GetString("StringLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Tapped.
        /// </summary>
        internal static string StringMessageTapped {
            get {
                return ResourceManager.GetString("StringMessageTapped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More from {0}.
        /// </summary>
        internal static string StringMoreFrom {
            get {
                return ResourceManager.GetString("StringMoreFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string StringName {
            get {
                return ResourceManager.GetString("StringName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEW.
        /// </summary>
        internal static string StringNew {
            get {
                return ResourceManager.GetString("StringNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string StringNext {
            get {
                return ResourceManager.GetString("StringNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no pending tasks today! :).
        /// </summary>
        internal static string StringNoPendingTasksToday {
            get {
                return ResourceManager.GetString("StringNoPendingTasksToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        internal static string StringNotification {
            get {
                return ResourceManager.GetString("StringNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string StringOK {
            get {
                return ResourceManager.GetString("StringOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string StringPassword {
            get {
                return ResourceManager.GetString("StringPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHOTOS.
        /// </summary>
        internal static string StringPhotos {
            get {
                return ResourceManager.GetString("StringPhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm your email address.
        /// </summary>
        internal static string StringPleaseConfirmAddress {
            get {
                return ResourceManager.GetString("StringPleaseConfirmAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please contact support center.
        /// </summary>
        internal static string StringPleaseContactSupport {
            get {
                return ResourceManager.GetString("StringPleaseContactSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        internal static string StringPrevious {
            get {
                return ResourceManager.GetString("StringPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready made UI&apos;s for Xamarin.Forms..
        /// </summary>
        internal static string StringReadyMadeUIsForXamarin {
            get {
                return ResourceManager.GetString("StringReadyMadeUIsForXamarin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Richard Stainford.
        /// </summary>
        internal static string StringRichardStainford {
            get {
                return ResourceManager.GetString("StringRichardStainford", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Robert Stainford.
        /// </summary>
        internal static string StringRobertStainford {
            get {
                return ResourceManager.GetString("StringRobertStainford", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string StringSave {
            get {
                return ResourceManager.GetString("StringSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        internal static string StringSaveChanges {
            get {
                return ResourceManager.GetString("StringSaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to screens.
        /// </summary>
        internal static string StringScreens {
            get {
                return ResourceManager.GetString("StringScreens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string StringSend {
            get {
                return ResourceManager.GetString("StringSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        internal static string StringShare {
            get {
                return ResourceManager.GetString("StringShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up!.
        /// </summary>
        internal static string StringSignUp {
            get {
                return ResourceManager.GetString("StringSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Society Pass.
        /// </summary>
        internal static string StringSocietyPass {
            get {
                return ResourceManager.GetString("StringSocietyPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something wrong here.
        /// </summary>
        internal static string StringSomethingWrongHere {
            get {
                return ResourceManager.GetString("StringSomethingWrongHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string StringState {
            get {
                return ResourceManager.GetString("StringState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string StringSuccess {
            get {
                return ResourceManager.GetString("StringSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You tapped on {0}&apos;s message..
        /// </summary>
        internal static string StringTappedOnAuthorMessage {
            get {
                return ResourceManager.GetString("StringTappedOnAuthorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You tapped on {0} context action..
        /// </summary>
        internal static string StringTappedOnContextAction {
            get {
                return ResourceManager.GetString("StringTappedOnContextAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter.
        /// </summary>
        internal static string StringTwitter {
            get {
                return ResourceManager.GetString("StringTwitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI.KIT.
        /// </summary>
        internal static string StringUIKIT {
            get {
                return ResourceManager.GetString("StringUIKIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string StringUsername {
            get {
                return ResourceManager.GetString("StringUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string StringWarning {
            get {
                return ResourceManager.GetString("StringWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to The Society Pass!.
        /// </summary>
        internal static string StringWelcomeToSocietyPass {
            get {
                return ResourceManager.GetString("StringWelcomeToSocietyPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have a new follower.
        /// </summary>
        internal static string StringYouHaveANewFollower {
            get {
                return ResourceManager.GetString("StringYouHaveANewFollower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have a new message.
        /// </summary>
        internal static string StringYouHaveANewMessage {
            get {
                return ResourceManager.GetString("StringYouHaveANewMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Account.
        /// </summary>
        internal static string StringYourAccount {
            get {
                return ResourceManager.GetString("StringYourAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip Code.
        /// </summary>
        internal static string StringZipCode {
            get {
                return ResourceManager.GetString("StringZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friends.
        /// </summary>
        internal static string TabItemTextFriends {
            get {
                return ResourceManager.GetString("TabItemTextFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UXDIVERS.
        /// </summary>
        internal static string UXDIVERS {
            get {
                return ResourceManager.GetString("UXDIVERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter required information.
        /// </summary>
        internal static string ValidationErrorEnterRequiredInfo {
            get {
                return ResourceManager.GetString("ValidationErrorEnterRequiredInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! This is just a friendly warning.
        /// </summary>
        internal static string ValidationWarningOops {
            get {
                return ResourceManager.GetString("ValidationWarningOops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn.
        /// </summary>
        internal static string WalkthroughHeaderLearn {
            get {
                return ResourceManager.GetString("WalkthroughHeaderLearn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Time.
        /// </summary>
        internal static string WalkthroughHeaderSaveTime {
            get {
                return ResourceManager.GetString("WalkthroughHeaderSaveTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string WalkthroughHeaderWelcome {
            get {
                return ResourceManager.GetString("WalkthroughHeaderWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn while you do.
        ///The Society Pass has tones of examples for you to play..
        /// </summary>
        internal static string WalkthroughTextLearn {
            get {
                return ResourceManager.GetString("WalkthroughTextLearn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save countless hours of UI design.
        ///Focus on what you do best..
        /// </summary>
        internal static string WalkthroughTextSaveTime {
            get {
                return ResourceManager.GetString("WalkthroughTextSaveTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To a new world of posibilities,
        ///welcome to The Society Pass UI Kit..
        /// </summary>
        internal static string WalkthroughTextWelcome {
            get {
                return ResourceManager.GetString("WalkthroughTextWelcome", resourceCulture);
            }
        }
    }
}
